# Generated by Django 3.2.5 on 2021-08-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentmode',
            field=models.CharField(max_length=100),
        ),
    ]
