# Generated by Django 3.2.5 on 2021-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
    ]
