# Generated by Django 3.2.5 on 2021-08-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkiosk', '0002_alter_order_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentmode',
            field=models.CharField(choices=[('CH', 'Cash'), ('CD', 'Card')], max_length=100),
        ),
    ]
