# Generated by Django 3.2.5 on 2021-08-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webkiosk', '0008_alter_customer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='number',
        ),
    ]
