# Generated by Django 3.2.5 on 2021-08-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkiosk', '0009_remove_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.BigIntegerField(default=0),
        ),
    ]
