# Generated by Django 3.2.5 on 2021-08-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkiosk', '0010_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.BigIntegerField(),
        ),
    ]
