# Generated by Django 3.2.5 on 2021-08-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkiosk', '0011_alter_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='number',
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
